name: Changelog
on:
  push:
    branches-ignore:
      - master


jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md

      - name: Commit the changelog
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(release): Update changelog [skip ci]"
          file_pattern: 'CHANGELOG.md'